// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TaskCreateDataInput struct {
	Name     string  `json:"name"`
	Content  *string `json:"content"`
	Finished *bool   `json:"finished"`
}

type TaskUpdateDataInput struct {
	Name     *string `json:"name"`
	Content  *string `json:"content"`
	Finished *bool   `json:"finished"`
}

type TaskUpdateInput struct {
	Name     *string `json:"name"`
	Content  *string `json:"content"`
	Finished *bool   `json:"finished"`
}

type WhereUniqueInput struct {
	ID string `json:"id"`
}
